### ISSUE TITLE
See console output of profiled process

### ISSUE THREAD

**Issue by sfiruch** [xoofx/ultra#7]
While profiling console applications, it'd be nice to see the outputs of the process to StdOut and StdErr. It appears that ultra swallows all console output while profiling.

**Comment by xoofx** [comment]
> While profiling console applications, it'd be nice to see the outputs of the process to StdOut and StdErr. It appears that ultra swallows all console output while profiling.

Yes, initially because I'm using Spectre.Console live update and it doesn't play well with a concurrent console output. I could provide a mode that disable it. I could also provide a mode that constantly capture the last e.g. 10 lines and display them in the live output. Both options are probably worth having in the end. Thoughts?

**Comment by sfiruch** [comment]
Spectre.Console is looking great, as always :)

I was planning to integrate Ultra into a CI pipeline, to automatically record profiles of performance tests. For my specific use-case, I think the ideal solution would be a command-line switch to mix the Ultra-output with program output (and to, sadly, disable the Spectre.Console-powered animations)
